import { z } from 'zod';

export const requestPayoutSchema = z.object({
  /** Optional. Omitted means "everything" — the original behaved that way and
   *  users expect it. Capped server-side at the real balance. */
  amountKobo: z.number().int().min(0).optional(),
  bankName: z.string().min(2).max(100),
  accountNumber: z.string().min(8).max(20),
  accountName: z.string().min(2).max(120),
  /** Client-supplied so a retry after a dropped connection cannot create a
   *  second withdrawal. Generated by the client per request attempt. */
  idempotencyKey: z.string().min(8).max(200).optional(),
});
export type RequestPayoutDto = z.infer<typeof requestPayoutSchema>;

export const socialTagSchema = z.object({
  handle: z.string().min(2).max(80),
});
export type SocialTagDto = z.infer<typeof socialTagSchema>;

export const updatePayoutStatusSchema = z.object({
  status: z.enum(['approved', 'paid', 'rejected']),
  reason: z.string().min(3).max(300).optional(),
});
export type UpdatePayoutStatusDto = z.infer<typeof updatePayoutStatusSchema>;
