import {
  WebSocketGateway,
  WebSocketServer,
  SubscribeMessage,
  OnGatewayConnection,
  MessageBody,
  ConnectedSocket,
} from '@nestjs/websockets';
import { UseFilters } from '@nestjs/common';
import { Server, Socket } from 'socket.io';
import { z } from 'zod';
import { getFirebaseAuth } from '../auth/firebase-admin';
import { ChatService } from './chat.service';
import { UsersService } from '../users/users.service';
import { socketCorsOrigins } from '../common/socket-cors';
import { GatewayExceptionFilter } from '../common/gateway-exception.filter';

const joinConversationSchema = z.object({ conversationId: z.string().uuid() });

// Typing notifications are ephemeral (never persisted) and deliberately
// tiny — a conversation id and nothing else. The server injects the
// sender's identity, so a client can't claim to be someone else.
const typingSchema = z.object({
  conversationId: z.string().uuid(),
  isTyping: z.boolean(),
});
const sendMessageSchema = z.object({
  conversationId: z.string().uuid(),
  // Idempotency key generated by the sending client. The sender shows an
  // optimistic bubble immediately, and this same event is broadcast back to it
  // (the broadcast goes to the whole room, sender included). Echoing this key
  // back is what lets the sender recognise its own message and reconcile it
  // with that bubble instead of rendering a second copy.
  //
  // Bounded and optional: older clients that don't send it still work.
  clientId: z.string().min(1).max(120).optional(),
  content: z.string().min(1).max(5000).optional(),
  mediaUrl: z.string().url().optional(),
  mediaType: z.enum(['image', 'video', 'voice', 'document']).optional(),
  audioDurationSec: z.number().optional(),
  fileName: z.string().optional(),
  fileSize: z.string().optional(),
}).refine((d) => d.content || d.mediaUrl, {
  message: 'Message must have content or media',
});

@WebSocketGateway({ cors: { origin: socketCorsOrigins(), credentials: true } })
@UseFilters(GatewayExceptionFilter)
export class ChatGateway implements OnGatewayConnection {
  // The `!` is required: Nest injects this after construction, so it is
  // genuinely unassigned in the constructor. Without it, TypeScript 6+ rejects
  // the file with TS2564 ("has no initializer and is not definitely assigned")
  // even though TypeScript 5.x accepted it — which means an editor running a
  // newer TypeScript than the build shows an error the build does not.
  @WebSocketServer() server!: Server;

  constructor(
    private readonly chatService: ChatService,
    private readonly usersService: UsersService,
  ) {}

  // Sockets don't go through Nest's HTTP guards, so we verify the
  // Firebase token manually the moment a socket connects — same idea
  // as FirebaseAuthGuard, just a different transport.
  async handleConnection(client: Socket) {
    try {
      const token = client.handshake.auth?.token as string | undefined;
      if (!token) throw new Error('no token');

      const decoded = await getFirebaseAuth().verifyIdToken(token);
      const dbUser = await this.usersService.findOrCreateByFirebaseUid({
        uid: decoded.uid,
        email: decoded.email,
        name: decoded.name,
        picture: decoded.picture,
      });

      client.data.userId = dbUser.id; // our Postgres user id, not the firebase uid
    } catch (err: any) {
      // This used to be a bare `catch { client.disconnect(); }` — the same silent
      // failure that was fixed in call.gateway.ts, and it had a second
      // consequence: `client.data.userId` stayed undefined, so any
      // `join_conversation` / `typing` / `send_message` already in flight ran with
      // an undefined id and threw a second, even less readable error out of the
      // handler. Nothing in the logs connected the two.
      const reason = err?.code || err?.errorInfo?.code || err?.message || 'unknown';
      console.error(`[chat] socket ${client.id} rejected: ${reason}`);
      client.emit('auth:error', { reason: String(reason) });
      setTimeout(() => client.disconnect(), 250);
    }
  }

  @SubscribeMessage('join_conversation')
  async handleJoin(
    @ConnectedSocket() client: Socket,
    @MessageBody() rawData: unknown,
  ) {
    const parsed = joinConversationSchema.safeParse(rawData);
    if (!parsed.success) return;
    const data = parsed.data;

    const allowed = await this.chatService.isParticipant(
      data.conversationId,
      client.data.userId,
    );
    if (!allowed) {
      // Return without joining (never leak whether the conversation exists), but
      // LOG it. This used to be a bare `return`, which meant a user who could not
      // join their own conversation's room produced no evidence anywhere — while
      // the client's socket still looked perfectly connected and simply received
      // nothing. That is the failure the live test surfaced as "one account can
      // send and receive, the other cannot".
      //
      // `userId` undefined means this socket never authenticated (handleConnection
      // failed) and every handler on it is a no-op.
      console.warn(
        `[chat] join refused: socket ${client.id} ` +
          `userId=${client.data.userId ?? 'UNAUTHENTICATED'} ` +
          `conversationId=${data.conversationId}`,
      );
      return;
    }

    client.join(data.conversationId); // Socket.IO "room" = one conversation
  }

  /**
   * Typing indicator. Replaces the old Firestore `presence` document
   * write, which every client subscribed to. Only participants of the
   * conversation receive the event, and the sender is taken from the
   * authenticated socket rather than the payload.
   */
  @SubscribeMessage('typing')
  async handleTyping(
    @ConnectedSocket() client: Socket,
    @MessageBody() rawData: unknown,
  ) {
    const parsed = typingSchema.safeParse(rawData);
    if (!parsed.success) return;
    const { conversationId, isTyping } = parsed.data;

    const allowed = await this.chatService.isParticipant(
      conversationId,
      client.data.userId,
    );
    if (!allowed) return;

    client.to(conversationId).emit('typing', {
      conversationId,
      userId: client.data.userId,
      isTyping,
    });
  }

  @SubscribeMessage('send_message')
  async handleMessage(
    @ConnectedSocket() client: Socket,
    @MessageBody() rawData: unknown,
  ) {
    // Best-effort identity for the failure report below. The client's idempotency
    // key is what the sender's optimistic bubble is keyed on, so echoing it back
    // is what lets the app show "Not sent" on the right message instead of
    // leaving it looking delivered.
    const raw = (rawData ?? {}) as { conversationId?: string; clientId?: string };

    const parsed = sendMessageSchema.safeParse(rawData);
    if (!parsed.success) {
      console.warn(`[chat] send rejected (invalid payload): socket ${client.id}`);
      client.emit('message:error', {
        conversationId: raw.conversationId,
        clientId: raw.clientId,
        reason: 'invalid-payload',
      });
      return;
    }
    const data = parsed.data;

    const allowed = await this.chatService.isParticipant(
      data.conversationId,
      client.data.userId,
    );
    if (!allowed) {
      console.warn(
        `[chat] send refused (not a participant): socket ${client.id} ` +
          `userId=${client.data.userId ?? 'UNAUTHENTICATED'} ` +
          `conversationId=${data.conversationId}`,
      );
      client.emit('message:error', {
        conversationId: data.conversationId,
        clientId: data.clientId,
        reason: 'not-a-participant',
      });
      return;
    }

    let message;
    try {
      message = await this.chatService.sendMessage(
        data.conversationId,
        client.data.userId,
        {
          content: data.content,
          mediaUrl: data.mediaUrl,
          mediaType: data.mediaType,
          audioDurationSec: data.audioDurationSec,
          fileName: data.fileName,
          fileSize: data.fileSize,
          clientId: data.clientId,
        },
      );
    } catch (err: any) {
      // A storage failure must not look like a delivered message. The client
      // sets its bubble to 'sent' the moment it emits, so without this the sender
      // is told nothing and the message simply never arrives for anyone.
      console.error(
        `[chat] send failed for socket ${client.id} (conversation ${data.conversationId}):`,
        err?.code ?? err?.message ?? err,
      );
      client.emit('message:error', {
        conversationId: data.conversationId,
        clientId: data.clientId,
        reason: err?.code || err?.message || 'send-failed',
      });
      return;
    }

    // Broadcast to every socket in the room, including the sender —
    // this is what fixes "one-sided delivery": both participants get
    // the same event from the same source of truth, no per-client
    // Firestore listener race.
    //
    // `message.clientId` rides along so the sender can match this echo to the
    // optimistic bubble it already rendered. Without it the sender has no way
    // to connect the two and shows the message twice. It comes straight from
    // the inserted row, so the socket echo and REST history carry the same
    // value and the client can dedupe on either.
    this.server.to(data.conversationId).emit('new_message', message);
  }
}
